nelmio_api_doc:
    documentation:
        info:
            title: Jmenu
            description: Menu
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1/restaurant(?!/doc$)
            - ^/api/v1/table(?!/doc$)
