version: "2"
services:

  nginx:
    image: nginx:alpine
    container_name: nginx_just_menu
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - fpm
    networks:
      - just-menu

  fpm:
    image: koshpaevsv/php7.4
    container_name: fpm_just_menu
    user: 1000:1000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000
    links:
      - mysql
    networks:
      - just-menu

  mysql:
    image: mysql:8
    container_name: mysql_just_menu
    command: ["--default-authentication-plugin=mysql_native_password", "--max_allowed_packet=256M"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123root"
      MYSQL_DATABASE: "just_menu"
      MYSQL_USER: "jmenu"
      MYSQL_PASSWORD: "123justMENU"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql/
      - ./logs/mysql:/var/log/mysql
    networks:
      - just-menu

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025
      - 1080:1080
    networks:
      - just-menu

networks:
  just-menu:
    driver: bridge
