### Создание User
POST http://localhost:8000/api/v1/users/ HTTP/1.1
Content-Type: application/json

{
  "name": "григорий лепс",
  "email": "leps-test-7@mail.ru",
  "phone": "99922029292",
  "position": "administrator",
  "password": "1111"
}

###

### Получение всех ресторанов User (на основе токена jwt)
GET http://localhost:8000/api/v1/users/restaurants
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2MDMwMDE5NTksInVzZXIiOiJ7XCJ1dWlkXCI6W10sXCJuYW1lXCI6XCJcXHUwNDJlXFx1MDQzN1xcdTA0MzVcXHUwNDQwMSBcXHUwNDJlXFx1MDQzN1xcdTA0MzVcXHUwNDQwXFx1MDQzZVxcdTA0MzJcXHUwNDM4XFx1MDQ0NzFcIixcImVtYWlsXCI6XCJ1c2VyMUBqdXN0LW1lbnUucnVcIn0ifQ.yCIsKhcgfNXKVQnhuk2WmsoFPQ46d648Bf7h8guaUiO5fj6rTFYJwP6dzohXeC3akj0mP1jh-OaVv_Trz5GrecwsHWYHooXSkL8Bhh0l_3qSmhjuvI9w_QmqZ4jzOVEcW59BY_Bai3cxRB8iS4waH8MdTmG5jAYIuA64x48t9JL60RmsoA_lxbeWVJsM5fXbFgq3xYY_V-Q7KmdewuaCEM5Cha4e-WzjgL21hyQZXfbcQAaaxl4iUrLG0IV1bGb5qDpXSUd7I2oRhnfdcQX0qQJ7HtMT3nDQbTgmFE77SVrAusab_vfx4jEyPFsdWsKwZb2bvFcGb_vw1lNpWjHFXrIpXYTh4ASHYmIqaKXnlcZCH-cv5oG10CdkniG6_bNNr2j51Nu5HGCFPw6XwWLu7kwjf38XeRGajG3lU7glMiOEGE05G628C_UvH-Vr0eabmicUX4KSwgPEUuGnBBF-7BMKj1PpQUntguGHEk9CzoCF4es1tpOKWuOlKv9pRd23k-JM7Z38BByUuBwo_AhgzYTM4C6z0u0OvzFWFjnOewi9JWRSNtBWWvuY-V9JYuEwcHZwoe5t8NFPDZoVotGAW4SUpm6RoO4scyOwvxNXzizZqqGpbY9qOwEZeDXKwwj1RoWwCjmvRJ1UUaEzTC6InpmKBhwSGM2BkeS5HDj70y0
Content-Type: application/json

###


### Получение юзера
GET http://localhost:8000/api/v1/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2MDMwMDAyNDMsInVzZXIiOiJ7XCJ1dWlkXCI6W10sXCJuYW1lXCI6XCJcXHUwNDJlXFx1MDQzN1xcdTA0MzVcXHUwNDQwMSBcXHUwNDJlXFx1MDQzN1xcdTA0MzVcXHUwNDQwXFx1MDQzZVxcdTA0MzJcXHUwNDM4XFx1MDQ0NzFcIixcImVtYWlsXCI6XCJ1c2VyMUBqdXN0LW1lbnUucnVcIn0ifQ.avpJjwLecSMQegbzI25as03pH-pKL-SMV11UlAdfAEmZebzghtZGkyxt9oWUnM7XcaYhJXtLmv_cfIik6SFlfjNY4XmzGTHVWFQToH0F_giIZRyYsLThxHWWDt2ghUmrujn0oC8CbHHar6gWWlswFLfbhBTlRBFFUpsWtLSHHA10cXjIo3jWLSGEnFL6Wav1lzcGJWilEug2QO2MXjKVLWgrnRzjPFZ27V4gXmm90yLF7mG_aClRPoQj3CqP_OYtVUCYAf9yvDzTJ9kDXcCKgb9f9d1f8piDfFq-nUVF2V5-S4eS1s_gR-1ZJOlzF05Kfo3XqPMOrGgHpLGou3Ft5YYYxfZDMYU_nev25dQL-UWyyZKuAh0__fConlBVVyQk71tTDW_MLCLuqym7sX-FJt_XMc-T9Qv4xVWcXj4pdfFpkJm0fA7YRuKdHcgZVrzNfXJqFlGXJU7Eo8mTdYYawBlywRTuQDq6qqg59N3i8tKlsf2UulQKN3jvoSve8jJfPimRfsv5fYOvn1OtCE5w47X-mcikynyLn_E9ewpYcrd5VbLzEZ1aH6qJkt69kJNKfUyXj5NyRFB9Gd1n-FoiF8-jI80Guf5NQXE56dhjmB_CJcI2CpPYcTiVIMMliM4RvcUOTbwp_Oh4DCbcvAhn-KRCOqy9TPJU6kBWDpvgbpY
Content-Type: application/json

###

### Получение юзера по uuid
GET http://localhost:8000/api/v1/users/1171a376-f6d7-4f3f-8b1c-7be79854abbd
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2MDMwMDAyNDMsInVzZXIiOiJ7XCJ1dWlkXCI6W10sXCJuYW1lXCI6XCJcXHUwNDJlXFx1MDQzN1xcdTA0MzVcXHUwNDQwMSBcXHUwNDJlXFx1MDQzN1xcdTA0MzVcXHUwNDQwXFx1MDQzZVxcdTA0MzJcXHUwNDM4XFx1MDQ0NzFcIixcImVtYWlsXCI6XCJ1c2VyMUBqdXN0LW1lbnUucnVcIn0ifQ.avpJjwLecSMQegbzI25as03pH-pKL-SMV11UlAdfAEmZebzghtZGkyxt9oWUnM7XcaYhJXtLmv_cfIik6SFlfjNY4XmzGTHVWFQToH0F_giIZRyYsLThxHWWDt2ghUmrujn0oC8CbHHar6gWWlswFLfbhBTlRBFFUpsWtLSHHA10cXjIo3jWLSGEnFL6Wav1lzcGJWilEug2QO2MXjKVLWgrnRzjPFZ27V4gXmm90yLF7mG_aClRPoQj3CqP_OYtVUCYAf9yvDzTJ9kDXcCKgb9f9d1f8piDfFq-nUVF2V5-S4eS1s_gR-1ZJOlzF05Kfo3XqPMOrGgHpLGou3Ft5YYYxfZDMYU_nev25dQL-UWyyZKuAh0__fConlBVVyQk71tTDW_MLCLuqym7sX-FJt_XMc-T9Qv4xVWcXj4pdfFpkJm0fA7YRuKdHcgZVrzNfXJqFlGXJU7Eo8mTdYYawBlywRTuQDq6qqg59N3i8tKlsf2UulQKN3jvoSve8jJfPimRfsv5fYOvn1OtCE5w47X-mcikynyLn_E9ewpYcrd5VbLzEZ1aH6qJkt69kJNKfUyXj5NyRFB9Gd1n-FoiF8-jI80Guf5NQXE56dhjmB_CJcI2CpPYcTiVIMMliM4RvcUOTbwp_Oh4DCbcvAhn-KRCOqy9TPJU6kBWDpvgbpY
Content-Type: application/json

###